# Let NetworkManager manage all devices on this system
network:
        #  version: 2
        #  renderer: NetworkManager
        ethernets:
                ens160:
                      dhcp4: true
                ens193:
                        addresses: [192.168.247.112/24]
                ens224:
                        addresses: [192.168.247.101/24]
                ens256:
                        addresses: [192.168.248.194/24]

